#! /bin/bash
clear

echo ' __    __              _ _      '
echo '/ / /\ \ \___  _ __ __| | | ___ '
echo '\ \/  \/ / _ \|  __/ _  | |/ _ \'
echo ' \  /\  / (_) | | | (_| | |  __/'
echo '  \/  \/ \___/|_|  \__,_|_|\___|'

python3 wordle.py

exit
